prgrms-be-devcourse/NBE3-4-2-Team9

backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java, backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/main/java/com/backend/global/exception/GlobalException.java, backend/src/main/java/com/backend/global/response/GenericResponse.java, backend/src/test/java/com/backend/BackendApplicationTests.java
<br/>
<br/>
<br/>
resolves #19 
resolves #19 
- 기능에서 어떤 부분이
<br/>
=> [REFACTOR] G-01

backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/main/java/com/backend/global/security/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.java, backend/src/main/java/com/backend/global/security/handler/JwtLogoutSuccessHandler.java, backend/src/main/java/com/backend/global/security/handler/OAuth2LoginSuccessHandler.java
<br/>
<br/>
<br/>
- 에러 코드 자료형 변경
<br/>
=> [REFACTOR]: 에러 코드 자료형 변경 #21

backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/main/java/com/backend/global/security/handler/OAuth2LoginFailureHandler.java, backend/src/main/java/com/backend/global/security/handler/OAuth2LoginSuccessHandler.java, backend/src/main/java/com/backend/global/security/oauth/CustomOAuth2UserService.java, backend/src/main/java/com/backend/standard/util/JwtUtil.java, backend/src/test/java/com/backend/CategoryControllerTest.java, backend/src/test/java/com/backend/global/redis/TestRedisConfig.java, backend/src/test/java/com/backend/global/security/handler/OAuth2LoginSuccessHandlerTest.java, backend/src/test/java/com/backend/global/security/oauth/CustomOAuth2UserServiceTest.java, backend/src/test/java/com/backend/global/security/oauth/OAuth2AuthenticationTest.java, backend/src/test/resources/application-test.yml
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FIX] : U-02 #25

backend/src/main/java/com/backend/domain/jobposting/entity/ExperienceLevel.java, backend/src/main/java/com/backend/domain/jobposting/entity/JobPosting.java, backend/src/main/java/com/backend/domain/jobposting/entity/JobPostingStatus.java, backend/src/main/java/com/backend/domain/jobposting/entity/RequireEducate.java, backend/src/main/java/com/backend/domain/jobposting/entity/Salary.java, backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingJpaRepository.java, backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java, backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java, backend/src/main/java/com/backend/domain/jobskill/entity/JobSkill.java, backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.java, backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepository.java, backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepositoryImpl.java
<br/>
<br/>
<br/>
resolves #32 
close #32 
- 채용 공고 기본 엔티티 설계 및 리포지토리 추가
<br/>
=> [FEAT] J-01

backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.java, backend/src/main/java/com/backend/domain/user/service/UserService.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java, backend/src/test/java/com/backend/global/annotation/CustomWithMock.java, backend/src/test/java/com/backend/global/config/CustomWithSecurityContextFactory.java
<br/>
<br/>
<br/>
- 프로필 조회 기능 구현
- 추가적으로 조회할 항목들은 추후 추가 예정
<br/>
=> [FEAT] U-04 #27

backend/src/main/java/com/backend/domain/category/controller/CategoryController.java, backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java, backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.java, backend/src/main/java/com/backend/domain/category/entity/Category.java, backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java, backend/src/main/java/com/backend/domain/category/service/CategoryService.java, backend/src/main/java/com/backend/domain/user/entity/UserRole.java, backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java, backend/src/test/java/com/backend/domain/category/CategoryServiceTest.java, backend/src/test/java/com/backend/domain/category/TestSecurityConfig.java
<br/>
<br/>
<br/>
resolves #35 
close #35 
- 카테고리 수정하는 기능 구현하였고, 테스트까지 완료하였습니다.
<br/>
=> [FEAT] CG-03 #35

backend/src/main/java/com/backend/domain/category/controller/CategoryController.java, backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java, backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.java, backend/src/main/java/com/backend/domain/category/entity/Category.java, backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java, backend/src/main/java/com/backend/domain/category/service/CategoryService.java, backend/src/main/java/com/backend/domain/user/entity/UserRole.java, backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java, backend/src/test/java/com/backend/domain/category/CategoryServiceTest.java, backend/src/test/java/com/backend/domain/category/TestSecurityConfig.java
Reverts prgrms-be-devcourse/NBE3-4-2-Team9#46
=> Revert "Revert "[FEAT] CG-03 #35""

backend/src/main/java/com/backend/global/security/SecurityConfig.java, frontend/src/app/users/[id]/edit/page.tsx, frontend/src/app/users/[id]/page.tsx, frontend/src/components/Header.tsx
- 프로필 조회
- 프로필 수정
<br/>
<br/>
<br/>
<br/>
=> [FEAT] [FE] : U-01 ~ U-05

frontend/next.config.js, frontend/package-lock.json, frontend/package.json, frontend/src/api/axios.ts, frontend/src/api/jobPosting.ts, frontend/src/api/post.ts, frontend/src/app/job-posting/[id]/page.tsx, frontend/src/app/layout.tsx, frontend/src/app/page.tsx, frontend/src/app/post/page.tsx, frontend/src/components/Providers.tsx, frontend/src/components/job/JobPostingCard.tsx, frontend/src/types/job-posting/JobPostingPageResponse.ts, frontend/src/types/post/PostResponse.ts, frontend/src/utils/dateUtils.ts
<br/>
<br/>
<br/>
- 메인 페이지 레이아웃 설정
- 검색창 생성(기능은 미구현)
- 공고글 출력(세부조회는 미구현)
<br/>
=> [FEAT] [FE]: J-00FE

frontend/next.config.js, frontend/src/api/axios.ts, frontend/src/api/category.ts, frontend/src/api/post.ts, frontend/src/app/page.tsx, frontend/src/app/post/[id]/page.tsx, frontend/src/app/post/page.tsx, frontend/src/app/post/write/page.tsx, frontend/src/types/post/Category.ts, frontend/src/types/post/PostResponse.ts
- 메인 페이지 게시글 출력
- 게시글 목록 출력
- 상세 게시글 출력
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : J-00FE

frontend/src/api/auth.ts, frontend/src/app/admin/login/page.tsx, frontend/src/app/admin/page.tsx, frontend/src/app/admin/profile/page.tsx, frontend/src/components/common/Navbar.tsx, frontend/src/middleware.ts, frontend/src/types/auth/AuthResponse.ts, frontend/src/types/auth/AuthState.ts
- 카테고리 추가 기능 구현
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : B-01FE #64

backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java, backend/src/test/java/com/backend/domain/post/PostControllerTest.java, frontend/src/app/post/[id]/page.tsx
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : B-06FE #78

backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java, frontend/package-lock.json, frontend/package.json, frontend/src/app/chat/page.tsx, frontend/src/app/page.tsx, frontend/src/app/post/[id]/page.tsx, frontend/src/app/post/page.tsx, frontend/src/app/users/[id]/page.tsx, frontend/src/components/Header.tsx
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : B-07FE #86

backend/src/main/java/com/backend/domain/category/controller/CategoryController.java, backend/src/main/java/com/backend/domain/category/entity/Category.java, backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java, backend/src/main/java/com/backend/domain/category/service/CategoryService.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
<br/>
<br/>
<br/>
resolves #45 
close #45 
- 카테고리 삭제 기능 구현 완료하였고, 권한 제한 걸고 테스트 완료 했습니다.
- 카테고리 삭제할 때 포스트도 같이 삭제되게끔 구현했습니다.
<br/>
=> [FEAT] CG-04 #45 

backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.java, backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.java, backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingPageResponse.java, backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.java, backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.java, backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.java, backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.java, backend/src/main/java/com/backend/domain/jobskill/dto/JobSkillResponse.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java, backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
<br/>
<br/>
<br/>
- 채용 공고 상세 조회 추가
resolves #87 
close #87 
- 기능에서 어떤 부분이
<br/>
=> [FEAT] Feature/J-02

backend/.gitignore, backend/src/main/java/com/backend/domain/comment/controller/CommentController.java, backend/src/main/java/com/backend/domain/comment/dto/request/CommentRequestDto.java, backend/src/main/java/com/backend/domain/comment/dto/response/CommentCreateResponseDto.java, backend/src/main/java/com/backend/domain/comment/entity/Comment.java, backend/src/main/java/com/backend/domain/comment/repository/CommentRepository.java, backend/src/main/java/com/backend/domain/comment/service/CommentService.java, backend/src/main/java/com/backend/domain/post/entity/Post.java, backend/src/main/java/com/backend/domain/post/service/PostService.java, backend/src/main/resources/templates/application-dev.yml
<br/>
<br/>
<br/>
- 댓글을 생성하는 기능을 구현하였습니다.
=> [FEAT] B-06

frontend/src/app/admin/profile/page.tsx, frontend/src/app/post/[id]/page.tsx, frontend/src/app/posts/page.tsx
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : R-00FE #91

backend/src/main/java/com/backend/domain/category/entity/Category.java, backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java, backend/src/main/java/com/backend/domain/post/dto/PostResponseDto.java, backend/src/main/java/com/backend/domain/post/entity/Post.java, backend/src/main/java/com/backend/domain/post/service/PostService.java, backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/test/java/com/backend/domain/post/PostControllerTest.java, backend/src/test/java/com/backend/domain/post/PostRepositoryTest.java
<br/>
<br/>
<br/>
resolves #67
close #67
- 게시글 상세 조회
- 로그인한 유저만 조회 가능
<br/>
=> [FEAT]B-02 #67

backend/build.gradle, backend/src/main/java/com/backend/BackendApplication.java, backend/src/main/java/com/backend/global/config/AsyncConfig.java, backend/src/main/java/com/backend/global/config/MailConfig.java, backend/src/main/java/com/backend/global/mail/service/MailService.java, backend/src/main/java/com/backend/global/mail/service/MailServiceImpl.java, backend/src/main/java/com/backend/global/mail/util/EmailTemplateMaker.java, backend/src/main/java/com/backend/global/mail/util/MailSender.java, backend/src/main/java/com/backend/global/mail/util/MailSenderImpl.java, backend/src/main/java/com/backend/global/mail/util/TemplateMaker.java, backend/src/main/java/com/backend/global/mail/util/TemplateName.java, backend/src/main/resources/mail-templates/recruitment-chat-template.html, backend/src/test/resources/application-test.yml
<br/>
<br/>
<br/>
resolves #96 
close #96 
- 모집 완료 메일 전송 기능 추가
<br/>
=> [FEAT] M-01

backend/src/main/java/com/backend/domain/user/entity/SiteUser.java, frontend/next-env.d.ts, frontend/src/api/axios.ts, frontend/src/app/admin/login/page.tsx, frontend/src/app/job-posting/[id]/page.tsx, frontend/src/app/job-posting/page.tsx, frontend/src/app/login/page.tsx, frontend/src/app/post/[id]/page.tsx, frontend/src/app/post/write/page.tsx
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : R-02FE #106

backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java, backend/src/main/java/com/backend/global/baseentity/BaseInitData.java, frontend/src/app/job-posting/[id]/page.tsx, frontend/src/app/job-posting/page.tsx, frontend/src/app/job-posting/voted/page.tsx, frontend/src/app/page.tsx, frontend/src/app/post/[id]/edit/page.tsx, frontend/src/app/post/[id]/page.tsx, frontend/src/app/post/page.tsx, frontend/src/app/post/recruitment/[id]/edit/page.tsx, frontend/src/app/post/recruitment/write/page.tsx, frontend/src/app/post/write/page.tsx, frontend/src/types/category.ts, frontend/src/types/post.ts, frontend/src/types/recruitmentStatus.ts
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : R-02FE #112

backend/src/main/java/com/backend/domain/comment/controller/ApiV1CommentController.java, backend/src/main/java/com/backend/domain/comment/dto/request/CommentRequestDto.java, backend/src/main/java/com/backend/domain/comment/dto/response/CommentModifyResponseDto.java, backend/src/main/java/com/backend/domain/comment/dto/response/CommentResponseDto.java, backend/src/main/java/com/backend/domain/comment/repository/CommentRepository.java, backend/src/main/java/com/backend/domain/comment/service/CommentService.java, backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.java, backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java, backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.java, backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/comment/ApiV1CommentControllerTest.java, backend/src/test/resources/sql/delete.sql, backend/src/test/resources/sql/init.sql
<br/>
<br/>
<br/>
- 댓글 조회 기능 구현하였습니다.
<br/>
=> [FEAT] B-09

backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingJpaRepository.java, backend/src/main/java/com/backend/domain/post/repository/PostQueryRepository.java, backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java, backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUserStatus.java, backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java, backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java, backend/src/main/java/com/backend/global/security/SecurityConfig.java, backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java, frontend/src/app/page.tsx, frontend/src/app/post/[id]/edit/page.tsx, frontend/src/app/post/[id]/page.tsx, frontend/src/app/post/page.tsx, frontend/src/app/post/recruitment/[id]/edit/page.tsx, frontend/src/app/users/[id]/page.tsx
<br/>
<br/>
<br/>
- 기능에서 어떤 부분이
<br/>
=> [FEAT] [FE] : R-04FE #115

backend/src/main/java/com/backend/domain/category/controller/CategoryController.java, backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java, backend/src/main/java/com/backend/domain/category/service/CategoryService.java, backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
<br/>
<br/>
<br/>
- CategoryService 추가 로직에 트랜잭션 추가해서 일관된 트랜잭션 관리
- CategoryController categorieList -> categoryList로 일관되게 수정, ResponseStatus 삭제
- CategoryConverter 메서드 이름 변경으로 가독성을 높임
<br/>
resolves #123 
close #123
=> CG-05 #123

backend/src/main/java/com/backend/domain/jobskill/constant/JobSkillConstant.java, backend/src/main/java/com/backend/global/baseentity/BaseInitData.java, backend/src/main/java/com/backend/global/redis/repository/RedisRepository.java, backend/src/main/java/com/backend/global/scheduler/service/SchedulerService.java, backend/src/test/java/com/backend/global/scheduler/SchedulerTest.java
<br/>
<br/>
<br/>
- RedisRepository에 hasKey, save 추가
- JobSkill Redis로 동기화하는 로직 추가
- SchedulerService에 JobPosting 전체 저장 메소드 위치 수정
- SchedulerService에 JobSkill을 DB(Mysql)조회하는 로직을 Redis로 변경
resolves #126 
close #126 
- 기능에서 어떤 부분이
<br/>
- 1100개 기준 성능 전 후 차이
- 개선 후 87% 성능 개선
=> [REFACTOR] J-01
